Repository apprentice-team-3/team-weekly-report, pull requests merged in 2024-03, with the labels that each got.

#120 README.mdの要件、ヘッダーの要件にプロジェクト一覧画面へのリンク表示を追記
  README.md
Labels: ヘッダー

#116 評価一覧画面を3/24(日)時点のワイアーフレームと対応させました
  README.md
Labels: 評価一覧画面

#98 parent_tasks, child_tasksのテーブルを踏まえてテーブルを設計
  SQL/create.sql
  SQL/exe.sql
Labels: SQL

#95 [README.mdの要件]画面共通要素ー＞ナビゲーションの手前に半角スペースを挿入
  README.md
Labels: ヘッダー, typo

#198 README.mdの要件、親タスク作成ポップアップのtypo修正
  README.md
Labels: typo, 親タスク作成ポップアップ

#202 データベースを日本語か対応させました
  SQL/exe.sql
Labels: SQL

#204 select.sqlファイルの作成 + プロジェクトテーブルからid = 1のプロジェクト名を取得
  SQL/select.sql
Labels: SQL, メンバータスク一覧画面

#209 使用するPHPファイルを追加
  src/evaluation.php
  src/member-task.php
Labels: メンバータスク一覧画面, 評価一覧画面

#217 exeファイルを1回目と2回目以降に分離しました
  SQL/after_the_second_time_exe.sql
  SQL/first_exe.sql
Labels: SQL

#219 特定のプロジェクトに対して親タスクを集計してプロジェクト全体の進捗を取得し、集計した結果を特定のプロジェクトのprogressへ反映
  SQL/after_the_second_time_exe.sql
  SQL/first_exe.sql
  SQL/select.sql
Labels: SQL

#229 子タスクの進捗を集計して親タスクの進捗に反映させる
  SQL/after_the_second_time_exe.sql
  SQL/first_exe.sql
  SQL/select.sql
Labels: SQL, メンバータスク一覧画面, 評価詳細ポップアップ

#260 プロジェクトのタイトルを見た目だけ表示する
  src/views/evaluation.php
  src/views/style.css
Labels: 評価一覧画面

#265 DBからprojectsのデータを取得してJSで整形後表示
  src/member-task.php
  src/views/member-task.php
  src/views/style.css
Labels: メンバータスク一覧画面

#267 git add . コマンド忘れ
  SQL/select.sql
  src/member-task.php
  src/models/parent_task.model.php
  src/models/user.model.php
  src/models/weekly_tasks.model.php
  src/views/member-task.php
  src/views/style.css
Labels: メンバータスク一覧画面

#293 メンバーごとに親タスクを表示。日付を修正。
  SQL/exe.sql
  SQL/update.sql
  src/services/common.php
  src/views/member-task.php
  src/views/style.css
Labels: メンバータスク一覧画面

#296 二週間分のサンプルデータを挿入。複数タスクにを登録できるように修正。CSSファイルを分割。
  SQL/exe.sql
  SQL/insert.sql
  src/evaluation.php
  src/member-task.php
  src/task-add-popup.php
  src/task-detail-popup.php
  src/views/css/evaluation_style.css
  src/views/css/member-task_style.css
  src/views/evaluation_layout.php
  src/views/member-task.php
  src/views/member-task_layout.php
Labels: メンバータスク一覧画面, exeファイルの更新あり

#301 progressバーを表示
  SQL/exe.sql
  SQL/insert.sql
  SQL/select.sql
  src/services/common.php
  src/views/css/member-task_style.css
  src/views/member-task.php
Labels: メンバータスク一覧画面, exeファイルの更新あり

#306 やらかしボンバー
  m1/exe.sql
Labels: exeファイルの更新あり, LGTM

#309 303 merge main popup
  src/popup.php
  src/views/css/popup/popup.css
  src/views/css/popup/popup.css.map
  src/views/css/popup/popup.scss
  src/views/js/member-task-js.php
  src/views/js/popup-handler-js.php
  src/views/js/task-add.js
  src/views/js/task-add.php
  src/views/member-task.php
  src/views/popup.php
  src/views/task-add-popup/task-add-popup-content.php
  src/views/task-add-popup/task-add-popup-template.php
  src/views/task-detail-popup/task-detail-popup-template.php
Labels: メンバータスク一覧画面, 親タスク作成ポップアップ

#319 進捗度バーを着色
  SQL/exe.sql
  src/api/post.php
  src/views/css/member-task_style.css
  src/views/js/member-task-js.php
  src/views/member-task.php
  src/views/member-task_layout.php
Labels: メンバータスク一覧画面, exeファイルの更新あり, LGTM

#328 タスク名を入力してタスク詳細ポップアップを表示し、親タスク、コメント、進捗を編集可能にし、個タスクが追加できるようにしました。
  src/api/child-tasks/fetch-all.php
  src/api/post.php
  src/api/update.php
  src/views/css/popup/popup.css
  src/views/css/popup/popup.css.map
  src/views/css/popup/popup.scss
  src/views/js/member-task-js.php
  src/views/js/popup-handler-js.php
  src/views/js/popup/add-popup.php
  src/views/js/popup/edit-popup.php
  src/views/js/task-add.js
  src/views/js/task-add.php
  src/views/member-task.php
  src/views/task-add-popup.php
  src/views/task-edit-popup/task-edit-popup-content.php
  src/views/task-edit-popup/task-edit-popup-template.php
Labels: タスク詳細ポップアップ
